### ISSUE TITLE
How to format message content ?

### ISSUE THREAD

**Issue by jerome-diver** [zhaoyao91/react-bootstrap-easy-dialog#2]
i can push text message inside the dialog box, but what if i want the message have line's jump (actually, '\n' char doesn't make new line).
Maybe it can also have a way to render an html content ? like html tag inside ?

**Comment by zhaoyao91** [comment]
you can pass any react element instead of a string as text. to break line, the snippet is like

```javascript
const confirmed = await dialog.alert(<div style={{ whiteSpace: "pre" }}>{"ni shuo ne \n haha"}</div>);
```

**Comment by jerome-diver** [comment]
thank you @zhaoyao91
